### PR TITLE
Babu Jahir Navaz is looking for new opportunities

### PR DESCRIPTION
**Pull request by jahirbnavaz**

### CODE REVIEW

**Comment by zfouts** [comment]
Please reach out to me on Slack :) Want to make sure you're part of our community before merging.

**Comment by jahirbnavaz** [comment]
Please let me know your Slack name/channel name to reach you.

Thanks,

Navaz.

**Comment by jjasghar** [comment]
Thanks for reaching out to our community, but we are targeting us the
Austin, Texas metro area. It looks like you said your in India, which is a
bit out of our scope.

Thanks though!

**Comment by jahirbnavaz** [comment]
Got it. Thank you.

**Pull request closed without merging**
